language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
addons:
  apt:
    packages:
    - gfortran
install:
- pip install -U coverage coveralls
- pip install -r requirements.pip
- pip install -r test_requirements.pip
script: nosetests --with-coverage
after_success: coveralls
deploy:
  provider: pypi
  skip_existing: true
  on:
    tags: true
  user: __token__
  password:
    secure: k13mML++2V/ryJY/soP3edm2bAVmkfDW9D+LgE6T8oTXEE7Y/RXCX2s5Pz2GAvmW1YyC7PeIlSR/P6mDxzJ0SCSFZSeD2lt4GEF8XAZacLmfvvy0NqofO6av+pH1H/rYpDrCarxqaQKKd90bd9MGQ6HguAh5M25M2Cv6bN8KdoUbssZQH0uuBtNt/piKY6/Pd6bhy451qmcDCrppTK1CNfsYZ5YvCrbpA5/9i9Ki5i3FkuZrNgZXpMgusLI7zD22yFEVOb/xoL6hgZ8q4vLCn/0fQhGPfnmg6KvhJk3nbw7IZe0+4OVm2gIaVyImEP4A+rPhmg0qFmy+h6vZOrdOknDzvW8cijnOkTNjR21ptHr/WlRyVYzgLknu5SYERiNSinGa6BDYl2YMlVYDeBvfMOqEepuTr2S8cWavTLKP9vpJhDxjfDvAalurKz87qjbi1WoCMG+wtAoE4YW1N9f6UcCwLbxG2lCenrEZGgjK810HEeKy6F+HKI4R6krviK1OWLEPJ1uiG5dYsLws1TtYJdmJ0V9jx1kqzuF1LArDY0uRo5nTAmAm4jLrdNDYE76CtfwjTwuylEnjSDd/tzPBWtht1Oi0NAYImmwMHhLXG2/SHAeKQPlttqLqTZfUkA06jg7lj5tZQUj44qcSAtOOJ5ZQnFDFDYDpjOgjq/+U7w0=
