language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
addons:
  apt:
    packages:
    - gfortran
install:
- pip install -U coverage coveralls
- pip install -r requirements.pip
- pip install -r test_requirements.pip
script: nosetests --with-coverage
after_success: coveralls
deploy:
  provider: pypi
  skip_existing: true
  on:
    tags: true
  user: __token__
  password:
    secure: OLTA5Z3cAlShi5S4n6eVwsShFIh+/j94mclArS+zjvOZdDAqTyYyS5cCdBiJ1ZGYqaJx5fF4KcVsnx8KUWkqGUaTefgMh1E+6MT/GjrnQbwTv3igtonPmakah3YyeHvQHJhWuKcMov3CkLgicGL/6uMK/ehjYW3F+tqHLtGx0eXgKmTbqt2XLUiCZqLl68Uu3dcWO4KjZtW0jjXhy1j9HlbcOOtLyJEiVVzun2Ujj4z3gKjqRUd3Ddlr3uoZpf9mL7sYLIKTajRD6NItI1wrn7oGDx3XLiK4z6WIBD2dI+DT54dWLQ+DgmfpTKUEVCS6vpVlOb1jxV1UdNSmqxtIH7Dv3uzsnIUxpc3OB5XZm4j7zJoGqpqPYmFoH2TDXUkDNiMx0Z+GJ31+wrkfb1WX9bLvW3gaAi+zTGDtzMqRuJtWhUwFLiWk75IhI3bQcRqPEQlrG4WPO1X6xjPXlkx7pe2cUyiHQGezrICfI3rRGHOQkbEVXHxy6cEnDku4nnZvg+RdAgL0lt+uDijGDkM6uHx4Lv+fA9qxu7Z99ZEC5FlyGdrOxI8r6Uc/+vIXog1qHraO75lrEQiifPI7LXYzMoaahDU2ZQy+cMvZHovLeNnD1hK+gmBqJkiJ2czUpbNBQBQ30m6IiDPfot33Y1ly58XNw+GoD9P4PTz9huHUJxE=
